### ISSUE TITLE
eventsJson2RMatrix not exported

### ISSUE THREAD

**Issue by lawwu** [7factory/RMixpanel#1]
Was this on purpose?

**Comment by ploner** [comment]
Yes. The method was intended for internal use However, it would make sense to put it into the exported methods, given it could be useful in standalone usage. I will change it.

**Comment by ploner** [comment]
Resolved on github. However, on CRAN the changes will take effect only with the next release, as the changes are minor.

**Comment by lawwu** [comment]
Thanks! Really appreciate your hard work on this package. I've found it incredibly useful.

**Comment by ploner** [comment]
Glad you find it such useful!
