### ISSUE TITLE
JSON related error: if a property is empty as <"property":{}> in each row of temp.txt, an error will pop up in mixpanelGetEvents() after scanning the file

### ISSUE THREAD

**Issue by Hdooster** [7factory/RMixpanel#2]
Hi,

I've found a bug that may or may not be related to JSON read-in in R. Be gentle, it's my first issue report anywhere. The error happens after using mixpanelGetEvents here:
```
## Scan...  Tue Jan 12 17:20:07 2016 
Read 66016 items
Error in matrix(unlist(value, recursive = FALSE, use.names = FALSE), nrow = nr,  :
'data' must be of a vector type, was 'NULL' 
```

This happens with a temp.txt with lines like this one:
```JSON
{"event":"Submit","properties":{"time":1430267687,"distinct_id":"14d0223b6f425c","$browser":"Internet Explorer","$initial_referrer":"https://www.google.gr","$initial_referring_domain":"www.google.gr","$lib_version":"2.4.2","$os":"Windows","$referrer":"www.mywebsite.com","$referring_domain":"www.mywebsite.com","$screen_height":768,"$screen_width":1024,"$search_engine":"google","bind":{},"mp_country_code":"GR","mp_lib":"web"}}
```

In which case 
```JSON
...,"bind":{},...
```
 is in each line. **It can be circumvented by setting the select argument in the mixpanelGetEvents function manually to all properties except for 'bind'.**
I don't know what bind is for now, nor do I have the time to find out. Maybe someone at our company messed up with setting up Mixpanel?

I found the error as follows: 

```
> x <- scan("C:/Users/Hendrik/Desktop/temp.txt", what=character(), sep="\n", quiet=F)
Read 66016 items
bad_data = jsonlite::fromJSON(paste("[", paste(x, collapse=","), "]")) 
```
Note that this last line is borrowed from **eventsJson2RMatrix.R, line 5**.

This is first read in as a data frame where, under properties, "bind" shows up as:

```
..$bind : 'data.frame' : 66016 obs. of 0 variables
```

An error pops up when trying to open this in RStudio's viewer as such:
```
> View(bad_data)
Error in View : 'names' attribute [1] must be the same length as the vector [0]
```

After selecting all properties but 'bind', things ran smoothly with mixpanelGetEvents.

**Comment by ploner** [comment]
Hi,

thank you for the good explanation about the issue. I do not know when Mixpanel includes the key 'bind' in its event properties. However, *eventsJson2RMatrix* had a problem with empty json values ("bind":{}). I made now a fix with should work. Pls let me know if you still encounter problems.

Best, M

**Comment by Hdooster** [comment]
Hi ploner, 
Thanks, I'll check it and confirm when there's time.
