### ISSUE TITLE
Subsetting results by multiples properties or constraints 

### ISSUE THREAD

**Issue by abshomali** [7factory/RMixpanel#3]
First off, let me thank you for an absolutely awesome package. Really made my life easier!

I can't seem to find a way to subset my results by more than one constraint or property when I use `mixpanelGetEvents`.  

For example: 

`mixpanelGetEvents(account, event = eventName, from = myDate, to = as.character(myDate), 
                                  daysPerBlock = 1, select=tableColumns
                                  where = 'properties["user_bucket"] > 8')`

The above works just fine. But if I try to get values for when `user_bucket` is greater than 8 AND less than 12, I either error out or get back 0 rows. Same thing for if I try to get values with the existing constraint and an additional one for another property, for example: `where = 'properties["os"] > "iPhone OS"'`

Is this supported in the package? 

Thanks!

**Comment by ploner** [comment]
Hi, happy you can benefit from my package :)

Regarding condition on more than 1 column: I tried y query on myself and it works. Maybe your syntax had an error? Here the code I used to test:

`events = mixpanelGetEvents(accountXYZ, from=20160101, to=20160102, where='properties["$os"]=="iPhone OS" and properties["$region"]=="California"')
*** Load events from 2016-01-01 to 2016-01-02 
## Download http://data.mixpanel.com/api/2.0/export/?api_key=...
## Scan...  Fri Feb 19 10:07:13 2016 
Read 85 items
dim(events)
[1] 85 62`

**Comment by ploner** [comment]
One more hint: maybe try replacing `properties["os"]` by `properties["$os"]`. Mixpanel's reserved properties start with a dollar sign ($). See also

https://mixpanel.com/help/questions/articles/special-or-reserved-properties

**Comment by abshomali** [comment]
Not only did you resolve the problem I asked about, you resolved another one that I was having but hadn't asked haha. Thanks!

Re: multiple constraints, yeah I think it was just a syntax thing. I was testing using "&" and "&&" in keeping with R's syntax and erroring out, but I guess it should be more like Python.

Re: the "$", I was having that problem but figured it has to do with our data and is unrelated to syntax. But I guess that takes care of it. Thanks again!

**Comment by ploner** [comment]
Super, happy I could help.

Btw, the "$" is ONLY for reserved properties. For custom properties the dollar is not needed.
