### ISSUE TITLE
Error in file(file, "r") : cannot open the connection

### ISSUE THREAD

**Issue by barmis** [7factory/RMixpanel#4]
Hello,

I try to use RMixpanel for getting data. But every time I get such mistake about unsuccessful connection:

Download [!part of query]...
!!! Retry...  Mon Apr 11 12:51:30 2016 
Scan...  Mon Apr 11 12:51:33 2016 

Error in file(file, "r") : cannot open the connection

In addition: Warning messages:
1: running command 'curl -s -S "[!query]"' had status 127 
2: In download.file(url, filePath, "curl", quiet = TRUE) :
  download had nonzero exit status
3: In file(file, "r") :
  cannot open file 'temp_f7b10c52-ffca-11e5-a555-5565855d2a60.txt': No such file or directory

I used [!part of query] and [query] for hiding Mixpanel query with API keys.

I checked for all API keys correctness several times. They are OK!

Could you help me with this problem?

**Comment by ploner** [comment]
Hello,
usually the _RMixpanel_ methods call the function _mixpanelGetData_ and download the json content into a temporary file (in your case 'temp_f7b10c52-ffca-11e5-a555-5565855d2a60.txt'). Then this file is opened, parsed and converted to an R object.
Try to debug by
    
    debug(mixpanelGetData)

After the call of

    code = download.file(url, filePath, "curl", quiet = TRUE)

you should check the _code_ and whether the temp file was created or not by

    file.exists(filepath)

**Comment by barmis** [comment]
Thank you for your answer!

I debugged several mixpanelGet*** functions and didn't find this temporary file you mentioned. Maybe there is something wrong with connection with Mixpanel and function can't get data from it. Is there any tool in package to test this connection.

**Comment by ploner** [comment]
You get code 127 on `download.file`, which means command not found (`curl`). Maybe `curl` is not installed on your system (you can try to call it on a terminal window). On Mac OS X I assume it is standard. So one possibility could be to install `curl`. Or, make a local copy of the method `mixpanelGetData` and overwrite the line

    code = download.file(url, filePath, "curl", quiet = TRUE)

by

    code = download.file(url, filePath, method="auto")

or another value for method. The documentation of `download.file` says:

> method: method to be used for downloading files. Current download methods are "internal", "wininet" (Windows only) "libcurl", "wget" and "curl", and there is a value "auto": see ‘Details’ and ‘Note’.
