### ISSUE TITLE
getting error in Matrix call

### ISSUE THREAD

**Issue by HarlanH** [7factory/RMixpanel#5]
```
> qq <- mixpanelGetEvents(acct, from="2016-05-01", verbose=TRUE)
*** Load events from 2016-05-01 to 2016-05-01 
## Download http://data.mixpanel.com/api/2.0/export/?api_key=xxx&expire=1465334793&from_date=2016-05-01&to_date=2016-05-01&sig=xxx...
## Scan...  Tue Jun  7 17:25:35 2016 
Read 341 items
Error in ncol(xj) : object 'xj' not found

Enter a frame number, or 0 to exit   

1: mixpanelGetEvents(acct, from = "2016-05-01", verbose = TRUE)
2: merge.matrix(alldata, eventsJson2RMatrix(data, select))
3: colnames(y)
4: is.data.frame(x)
5: eventsJson2RMatrix(data, select)
6: apply(ri, 1, function(z) paste(names(z), "=", z, sep = "", collapse = ","))
7: as.matrix(X)
8: as.matrix.data.frame(X)
9: ncol(xj)
```

When I trace through I can see that it's pulling the data, but something in the `eventsJson2RMatrix` is choking, and I'm unsure why. The individual `apply` calls are succeeding, but it's not able to collapse the result back down to a matrix.

**Comment by ploner** [comment]
Hi Harlan!
Maybe the resulting data is somewhat not conform to usual format. Try to debug carefully into eventsJson2RMatrix; or send me the object which fails - as long as there is no security concern.
Best, M

**Comment by HarlanH** [comment]
I'm no longer at the firm where I ran into this, so I can't replicate at this time. Closing the issue...
