### ISSUE TITLE
Curl not found (PC Only)

### ISSUE THREAD

**Issue by lucibelloj** [7factory/RMixpanel#6]
`res <- mixpanelJQLQuery(account, jqlQuery)` is resulting in the following error on PC only:

```
Error in system(curlCall, intern = TRUE, ignore.stderr = TRUE) : 
  'curl' not found
```

Tested and tried on multiple PCs and the full code stops there. Weirdly enough, the code works flawlessly on a Mac.

**Comment by ploner** [comment]
Hi,
the current version could be found on https://github.com/ploner/RMixpanel. Please use the latest release there and create an issue on https://github.com/ploner/RMixpanel if the error persists. Thanks.

**Comment by lucibelloj** [comment]
Hey @ploner, the ability to create an issue on the current version doesn't exist? Is this by design or an error?

**Comment by ploner** [comment]
The project is moved to github/Ploner please create an issue there. THX

Meinhard

Am 06.01.2017 7:40 nachm. schrieb "lucibelloj" <notifications@github.com>:

**Comment by ploner** [comment]
Hi @lucibelloj, 

I fixed the issue. Please download version 0.6-0 or later of the package from [https://github.com/ploner/RMixpanel](url) or from CRAN (available there within some hours).

**Comment by ploner** [comment]
Hi @lucibelloj,

now the current version also allows creating issues. It was a mistake of my side, thanks for the hint.

**Comment by lucibelloj** [comment]
@ploner Thank you! Just posted on the current version.

**Comment by ploner** [comment]
Welcome.
The version 0.6-0  is now on CRAN.
